/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.CustomerRole;

import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Role.CustomerRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rahuludhayakumar
 */
public class AddCustomer extends javax.swing.JPanel {

    /**
     * Creates new form AddCustomer
     */
    
       private CustomerDirectory customerDirectory;
    private JPanel container;
    private EcoSystem system;
    
    Customer customer = new Customer();
    public AddCustomer(JPanel container, EcoSystem system, CustomerDirectory custDir) {
        
                this.customerDirectory = custDir;
        this.system = system;
        this.container = container;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddCustomer = new javax.swing.JLabel();
        lblCustName = new javax.swing.JLabel();
        lblCustUserName = new javax.swing.JLabel();
        lblCustPass = new javax.swing.JLabel();
        lblCustContact = new javax.swing.JLabel();
        txtCustName = new javax.swing.JTextField();
        txtCustUserName = new javax.swing.JTextField();
        txtCustContact = new javax.swing.JTextField();
        lblCustEmail = new javax.swing.JLabel();
        txtCustEmail = new javax.swing.JTextField();
        lblCustAddr = new javax.swing.JLabel();
        txtCustAddr = new javax.swing.JTextField();
        lblCustZip = new javax.swing.JLabel();
        txtCustZip = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblAddCust = new javax.swing.JButton();
        pwCustPass = new javax.swing.JPasswordField();

        lblAddCustomer.setBackground(new java.awt.Color(204, 255, 255));
        lblAddCustomer.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lblAddCustomer.setForeground(new java.awt.Color(0, 51, 51));
        lblAddCustomer.setText("Add Customer");

        lblCustName.setBackground(new java.awt.Color(204, 255, 255));
        lblCustName.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblCustName.setForeground(new java.awt.Color(0, 51, 51));
        lblCustName.setText("Enter Full Name :");

        lblCustUserName.setBackground(new java.awt.Color(204, 255, 255));
        lblCustUserName.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblCustUserName.setForeground(new java.awt.Color(0, 51, 51));
        lblCustUserName.setText("Username :");

        lblCustPass.setBackground(new java.awt.Color(204, 255, 255));
        lblCustPass.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblCustPass.setForeground(new java.awt.Color(0, 51, 51));
        lblCustPass.setText("Password :");

        lblCustContact.setBackground(new java.awt.Color(204, 255, 255));
        lblCustContact.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblCustContact.setForeground(new java.awt.Color(0, 51, 51));
        lblCustContact.setText("Enter Contact No :");

        txtCustName.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtCustName.setForeground(new java.awt.Color(0, 51, 51));

        txtCustUserName.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtCustUserName.setForeground(new java.awt.Color(0, 51, 51));
        txtCustUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustUserNameActionPerformed(evt);
            }
        });

        txtCustContact.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtCustContact.setForeground(new java.awt.Color(0, 51, 51));

        lblCustEmail.setBackground(new java.awt.Color(204, 255, 255));
        lblCustEmail.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblCustEmail.setForeground(new java.awt.Color(0, 51, 51));
        lblCustEmail.setText("Enter Email ID:");

        txtCustEmail.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtCustEmail.setForeground(new java.awt.Color(0, 51, 51));

        lblCustAddr.setBackground(new java.awt.Color(204, 255, 255));
        lblCustAddr.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblCustAddr.setForeground(new java.awt.Color(0, 51, 51));
        lblCustAddr.setText("Enter Street Address :");

        txtCustAddr.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtCustAddr.setForeground(new java.awt.Color(0, 51, 51));

        lblCustZip.setBackground(new java.awt.Color(204, 255, 255));
        lblCustZip.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblCustZip.setForeground(new java.awt.Color(0, 51, 51));
        lblCustZip.setText("Enter Zip Code :");

        txtCustZip.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtCustZip.setForeground(new java.awt.Color(0, 51, 51));

        btnBack.setBackground(new java.awt.Color(204, 255, 255));
        btnBack.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 51, 51));
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblAddCust.setBackground(new java.awt.Color(204, 255, 255));
        lblAddCust.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblAddCust.setForeground(new java.awt.Color(0, 51, 51));
        lblAddCust.setText("Add");
        lblAddCust.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblAddCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblAddCustActionPerformed(evt);
            }
        });

        pwCustPass.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        pwCustPass.setForeground(new java.awt.Color(0, 51, 51));
        pwCustPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwCustPassActionPerformed(evt);
            }
        });
        pwCustPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pwCustPassKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwCustPassKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCustName, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwCustPass, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddCustomer))
                .addContainerGap(583, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(lblCustName))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(lblCustUserName))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(lblCustPass))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(lblCustContact)
                            .addGap(31, 31, 31)
                            .addComponent(txtCustContact, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(lblCustEmail)
                            .addGap(32, 32, 32)
                            .addComponent(txtCustEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblCustAddr)
                            .addGap(30, 30, 30)
                            .addComponent(txtCustAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(lblCustZip)
                            .addGap(30, 30, 30)
                            .addComponent(txtCustZip, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(118, 118, 118)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(69, 69, 69)
                            .addComponent(lblAddCust, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 568, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblAddCustomer)
                .addGap(56, 56, 56)
                .addComponent(txtCustName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCustUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwCustPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(3, 133, Short.MAX_VALUE)
                    .addComponent(lblCustName)
                    .addGap(12, 12, 12)
                    .addComponent(lblCustUserName)
                    .addGap(20, 20, 20)
                    .addComponent(lblCustPass)
                    .addGap(38, 38, 38)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(lblCustContact))
                        .addComponent(txtCustContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(8, 8, 8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(lblCustEmail))
                        .addComponent(txtCustEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(4, 4, 4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(lblCustAddr))
                        .addComponent(txtCustAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(6, 6, 6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(lblCustZip))
                        .addComponent(txtCustZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(16, 16, 16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnBack)
                        .addComponent(lblAddCust))
                    .addGap(0, 27, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CustomerDB manageCustomersJPanel = (CustomerDB) component;
        manageCustomersJPanel.populateCustomer();
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void lblAddCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblAddCustActionPerformed
        // TODO add your handling code here:

        String custName = txtCustName.getText();
        String custContact = txtCustContact.getText();
        String custAddr = txtCustAddr.getText();
        String custZipCode = txtCustZip.getText();
        String custUserName = txtCustUserName.getText();
        String custPass = String.valueOf(pwCustPass.getPassword());
        String custEmail = txtCustEmail.getText();

        if( custName.isEmpty() || custContact.isEmpty() || custAddr.isEmpty() || custZipCode.isEmpty() ||
            custUserName.isEmpty() || custPass.isEmpty() || custEmail.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Kindly Enter all the required fields!");
        }  
        
        else {

            customer.setCustID(customerDirectory.genCustID() );
            customer.setCustName(custName);
            customer.setCustAddr(custAddr);
            customer.setCustContact(custContact);
            customer.setCustEmail(custEmail);
            customer.setCustZipCode(custZipCode);
            customerDirectory.addCustomer(customer);
            Employee employee = system.getEmployeeDirectory().createEmployee(customer.getCustID());
            system.setCustomerDirectory(customerDirectory);
            UserAccount account = system.getUserAccountDirectory().createUserAccount(custUserName, custPass, employee, new CustomerRole());
            JOptionPane.showMessageDialog(null, "New Customer "+account.getUsername()+" added");
          //  resetFields();
        }
    }//GEN-LAST:event_lblAddCustActionPerformed

    private void pwCustPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwCustPassActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_pwCustPassActionPerformed

    private void pwCustPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwCustPassKeyReleased
        // TODO add your handling code here:
        //          int pwSize = pwCustPass.getText().length();
        //        System.out.println("PassKeyReleased PwSize :: "+pwSize);
        //        pbCustPassStr.setValue(pwSize);
    }//GEN-LAST:event_pwCustPassKeyReleased

    private void pwCustPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwCustPassKeyTyped
   
    }//GEN-LAST:event_pwCustPassKeyTyped

    private void txtCustUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustUserNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton lblAddCust;
    private javax.swing.JLabel lblAddCustomer;
    private javax.swing.JLabel lblCustAddr;
    private javax.swing.JLabel lblCustContact;
    private javax.swing.JLabel lblCustEmail;
    private javax.swing.JLabel lblCustName;
    private javax.swing.JLabel lblCustPass;
    private javax.swing.JLabel lblCustUserName;
    private javax.swing.JLabel lblCustZip;
    private javax.swing.JPasswordField pwCustPass;
    private javax.swing.JTextField txtCustAddr;
    private javax.swing.JTextField txtCustContact;
    private javax.swing.JTextField txtCustEmail;
    private javax.swing.JTextField txtCustName;
    private javax.swing.JTextField txtCustUserName;
    private javax.swing.JTextField txtCustZip;
    // End of variables declaration//GEN-END:variables
}
