/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.CustomerRole;

import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rahuludhayakumar
 */
public class CustomerDB extends javax.swing.JPanel {

    /**
     * Creates new form CustomerDB
     */
    
        public CustomerDirectory custDirectory;
    public JPanel container;
    public EcoSystem system;
    public CustomerDB(JPanel userProcessContainer, EcoSystem system, CustomerDirectory custDirectory) {
        initComponents();
        
                this.system = system;
        this.custDirectory = custDirectory;
        this.container = userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTblCustomers = new javax.swing.JTable();
        btnViewCust = new javax.swing.JButton();
        btnDelCust = new javax.swing.JButton();
        btnAddCust = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Customers Database");

        JTblCustomers.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        JTblCustomers.setForeground(new java.awt.Color(0, 51, 51));
        JTblCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Customer No", "Username", "Name", "Contact No", "Email", "Street Address", "Zipcode"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTblCustomers);

        btnViewCust.setBackground(new java.awt.Color(255, 255, 255));
        btnViewCust.setFont(new java.awt.Font("American Typewriter", 1, 12)); // NOI18N
        btnViewCust.setForeground(new java.awt.Color(0, 51, 51));
        btnViewCust.setText("View");
        btnViewCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCustActionPerformed(evt);
            }
        });

        btnDelCust.setBackground(new java.awt.Color(255, 255, 255));
        btnDelCust.setFont(new java.awt.Font("American Typewriter", 1, 12)); // NOI18N
        btnDelCust.setForeground(new java.awt.Color(0, 51, 51));
        btnDelCust.setText("Delete");
        btnDelCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelCustActionPerformed(evt);
            }
        });

        btnAddCust.setBackground(new java.awt.Color(255, 255, 255));
        btnAddCust.setFont(new java.awt.Font("American Typewriter", 1, 12)); // NOI18N
        btnAddCust.setForeground(new java.awt.Color(0, 51, 51));
        btnAddCust.setText("Add");
        btnAddCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("American Typewriter", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 51, 51));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddCust, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnViewCust, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(376, 376, 376)
                        .addComponent(btnDelCust, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelCust)
                    .addComponent(btnViewCust))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCust)
                    .addComponent(btnBack))
                .addContainerGap(170, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCustActionPerformed
        // TODO add your handling code here:
        int selectedRow = JTblCustomers.getSelectedRow();
        int count = JTblCustomers.getSelectedRowCount();
        if (count == 1) {
            if (selectedRow >= 0) {
                CardLayout layout = (CardLayout) container.getLayout();
                Customer customer = custDirectory.getCustomerId(selectedRow);
                UpdateCustomer viewUpdateCustomerJPanel = new UpdateCustomer(system, container, customer, custDirectory);
                container.add(viewUpdateCustomerJPanel);
                layout.next(container);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Select a Row to continue.");
        }
    }//GEN-LAST:event_btnViewCustActionPerformed

    private void btnDelCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelCustActionPerformed
        // TODO add your handling code here:
        int selectedRow = JTblCustomers.getSelectedRow();
        int count = JTblCustomers.getSelectedRowCount();
        if (count == 1) {
            if (selectedRow >= 0) {
                int selectionButton = JOptionPane.YES_NO_OPTION;
                int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete??", "Warning", selectionButton);
                if (selectionResult == JOptionPane.YES_OPTION) {
                    custDirectory.deleteCustomer(selectedRow, system);
                    populateCustomer();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Select a Row to continue.");
        }
    }//GEN-LAST:event_btnDelCustActionPerformed

    private void btnAddCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        AddCustomer createCustomersJPanel = new AddCustomer(container, system, custDirectory);
        container.add(createCustomersJPanel);
        layout.next(container);
    }//GEN-LAST:event_btnAddCustActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTblCustomers;
    private javax.swing.JButton btnAddCust;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelCust;
    private javax.swing.JButton btnViewCust;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void populateCustomer() {
            DefaultTableModel model = (DefaultTableModel) JTblCustomers.getModel();
        model.setRowCount(0);
        for (UserAccount userAcc : system.getUserAccountDirectory().getUserAccountList()) {
            for (Customer customer : custDirectory.getCustDir()) {
                if (customer.getCustID().equalsIgnoreCase(userAcc.getEmployee().getName())) {
                    Object[] row = new Object[7];
                    row[0] = customer.getCustID();
                    row[1] = userAcc.getUsername();
                    row[2] = customer.getCustName();
                    row[3] = customer.getCustContact();
                    row[4] = customer.getCustEmail();
                    row[5] = customer.getCustAddr();
                    row[6] = customer.getCustZipCode();
                    model.addRow(row);
                }
            }
        }   
    
    }
}
