/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.DeliveryManRole;

import Business.DeliveryMan.DeliveryMan;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Role.DeliverManRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rahuludhayakumar
 */
public class AddDeliveryman extends javax.swing.JPanel {

    private final DeliveryManDirectory deliveryManDirectory;
    private final EcoSystem system;
    private final JPanel container;
    public AddDeliveryman(JPanel container, EcoSystem system, DeliveryManDirectory deliveryManDirectory) {
        initComponents();
               this.deliveryManDirectory = deliveryManDirectory;
        this.system = system;
        this.container = container;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDeliName = new javax.swing.JLabel();
        lblDeliUserName = new javax.swing.JLabel();
        lblDeliPass = new javax.swing.JLabel();
        lblDeliContact = new javax.swing.JLabel();
        lblDeliEmail = new javax.swing.JLabel();
        txtDeliName = new javax.swing.JTextField();
        txtDeliUserName = new javax.swing.JTextField();
        pwDeliPass = new javax.swing.JPasswordField();
        txtDeliContact = new javax.swing.JTextField();
        txtDeliEmail = new javax.swing.JTextField();
        lblAddRest = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnAddRest = new javax.swing.JButton();

        lblDeliName.setBackground(new java.awt.Color(204, 255, 255));
        lblDeliName.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblDeliName.setForeground(new java.awt.Color(0, 51, 51));
        lblDeliName.setText("Enter Full Name :");

        lblDeliUserName.setBackground(new java.awt.Color(204, 255, 255));
        lblDeliUserName.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblDeliUserName.setForeground(new java.awt.Color(0, 51, 51));
        lblDeliUserName.setText("Set Username :");

        lblDeliPass.setBackground(new java.awt.Color(204, 255, 255));
        lblDeliPass.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblDeliPass.setForeground(new java.awt.Color(0, 51, 51));
        lblDeliPass.setText("Set Password :");

        lblDeliContact.setBackground(new java.awt.Color(204, 255, 255));
        lblDeliContact.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblDeliContact.setForeground(new java.awt.Color(0, 51, 51));
        lblDeliContact.setText("Enter Contact No :");

        lblDeliEmail.setBackground(new java.awt.Color(204, 255, 255));
        lblDeliEmail.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblDeliEmail.setForeground(new java.awt.Color(0, 51, 51));
        lblDeliEmail.setText("Enter Email ID :");

        txtDeliName.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtDeliName.setForeground(new java.awt.Color(0, 51, 51));

        txtDeliUserName.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtDeliUserName.setForeground(new java.awt.Color(0, 51, 51));

        pwDeliPass.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        pwDeliPass.setForeground(new java.awt.Color(0, 51, 51));
        pwDeliPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwDeliPassActionPerformed(evt);
            }
        });
        pwDeliPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pwDeliPassKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwDeliPassKeyTyped(evt);
            }
        });

        txtDeliContact.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtDeliContact.setForeground(new java.awt.Color(0, 51, 51));

        txtDeliEmail.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtDeliEmail.setForeground(new java.awt.Color(0, 51, 51));

        lblAddRest.setBackground(new java.awt.Color(204, 255, 255));
        lblAddRest.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lblAddRest.setForeground(new java.awt.Color(0, 51, 51));
        lblAddRest.setText("Add Delivery Person");

        btnBack.setBackground(new java.awt.Color(204, 255, 255));
        btnBack.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 51, 51));
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAddRest.setBackground(new java.awt.Color(204, 255, 255));
        btnAddRest.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnAddRest.setForeground(new java.awt.Color(0, 51, 51));
        btnAddRest.setText("Add");
        btnAddRest.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(lblAddRest))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDeliName)
                        .addGap(59, 59, 59)
                        .addComponent(txtDeliName, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDeliUserName)
                        .addGap(72, 72, 72)
                        .addComponent(txtDeliUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblDeliPass)
                        .addGap(73, 73, 73)
                        .addComponent(pwDeliPass, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblDeliContact)
                        .addGap(49, 49, 49)
                        .addComponent(txtDeliContact, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblDeliEmail)
                        .addGap(66, 66, 66)
                        .addComponent(txtDeliEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(btnAddRest, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(582, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblAddRest)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblDeliName))
                    .addComponent(txtDeliName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblDeliUserName))
                    .addComponent(txtDeliUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblDeliPass))
                    .addComponent(pwDeliPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblDeliContact))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(txtDeliContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblDeliEmail))
                    .addComponent(txtDeliEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAddRest, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(164, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pwDeliPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwDeliPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwDeliPassActionPerformed

    private void pwDeliPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwDeliPassKeyReleased
        // TODO add your handling code here
    }//GEN-LAST:event_pwDeliPassKeyReleased

    private void pwDeliPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwDeliPassKeyTyped
        // TODO add your handling code here:
    
    }//GEN-LAST:event_pwDeliPassKeyTyped

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DeliverymanDB manageDeliJPanel = (DeliverymanDB) component;
       // manageDeliJPanel.populateDeliveryManTable();
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRestActionPerformed
        // TODO add your handling code here:

        String custName = txtDeliName.getText();
        String custContact = txtDeliContact.getText();
        String custUserName = txtDeliUserName.getText();
        String custPass = String.valueOf(pwDeliPass.getPassword());
        String custEmail = txtDeliEmail.getText();

        if( custName.isEmpty() || custContact.isEmpty() ||
            custUserName.isEmpty() || custPass.isEmpty() || custEmail.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kindly Enter all the required fields!");
        }     else {
            DeliveryMan deliveryMan = new DeliveryMan();
            deliveryMan.setDeliName(custName);
            deliveryMan.setDeliPhoneNo(custContact);
            deliveryMan.setDeliEmail(custEmail);
            deliveryManDirectory.addDeliveryMan(deliveryMan);
            Employee employee = system.getEmployeeDirectory().createEmployee(deliveryMan.getDeliveryID());
            system.setDeliveryManDirectory(deliveryManDirectory);
            UserAccount account = system.getUserAccountDirectory().createUserAccount(custUserName, custPass, employee, new DeliverManRole());
            JOptionPane.showMessageDialog(null, "New Delivery Man "+account.getUsername()+" added to the System Successfully!");
            //resetFields();
        }
    }//GEN-LAST:event_btnAddRestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRest;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblAddRest;
    private javax.swing.JLabel lblDeliContact;
    private javax.swing.JLabel lblDeliEmail;
    private javax.swing.JLabel lblDeliName;
    private javax.swing.JLabel lblDeliPass;
    private javax.swing.JLabel lblDeliUserName;
    private javax.swing.JPasswordField pwDeliPass;
    private javax.swing.JTextField txtDeliContact;
    private javax.swing.JTextField txtDeliEmail;
    private javax.swing.JTextField txtDeliName;
    private javax.swing.JTextField txtDeliUserName;
    // End of variables declaration//GEN-END:variables
}
