/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User_interface;

import java.awt.event.KeyEvent;
import model.PersonalData;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rahuludhayakumar
 */
public class createJpanel1 extends javax.swing.JPanel {

    /**
     * Creates new form createJpanel1
     */
   PersonalData personaldata;
    
    public createJpanel1(PersonalData personaldata) {
        initComponents();
        this.personaldata = personaldata;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSubmit = new javax.swing.JButton();
        lblCreate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        txtVehicleNumber = new javax.swing.JTextField();
        lblIP = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblHealthPlan = new javax.swing.JLabel();
        lblLinkedin = new javax.swing.JLabel();
        txtLicense = new javax.swing.JTextField();
        txtGeographicData = new javax.swing.JTextField();
        lblLicense = new javax.swing.JLabel();
        txtBank = new javax.swing.JTextField();
        txtIPAddress = new javax.swing.JTextField();
        lblMedicalRecordNumber = new javax.swing.JLabel();
        lblDeviceIdentifier = new javax.swing.JLabel();
        txtTelephone = new javax.swing.JTextField();
        txtFaxnumber = new javax.swing.JTextField();
        txtBiometric = new javax.swing.JTextField();
        lblBiometric = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtDevice = new javax.swing.JTextField();
        txtIdnumber = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        lblVehicleNumber = new javax.swing.JLabel();
        lblTelephonenumber = new javax.swing.JLabel();
        txtMedicalRecord = new javax.swing.JTextField();
        lblIDnumber = new javax.swing.JLabel();
        txtDob = new javax.swing.JTextField();
        lblMobileNumber = new javax.swing.JLabel();
        txtHealthplan = new javax.swing.JTextField();
        lblBankAccountNumber = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        txtLinkedin = new javax.swing.JTextField();
        lblDob = new javax.swing.JLabel();
        lblFaxNumber = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblGeographicData = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblCreate.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblCreate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreate.setText("Create");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        lblIP.setText("IP Address");

        lblHealthPlan.setText("Health Plan");

        lblLinkedin.setText("Linkedin");

        txtGeographicData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeographicDataActionPerformed(evt);
            }
        });

        lblLicense.setText("License Number");

        lblMedicalRecordNumber.setText("Medical Record Number");

        lblDeviceIdentifier.setText("Device Identifier");

        txtFaxnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaxnumberActionPerformed(evt);
            }
        });

        lblBiometric.setText("Biometric");

        txtMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobileActionPerformed(evt);
            }
        });
        txtMobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMobileKeyPressed(evt);
            }
        });

        jLabel2.setText("Photo");

        lblName.setText("Name");

        txtIdnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdnumberActionPerformed(evt);
            }
        });

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });

        lblVehicleNumber.setText("Vehicle Number");

        lblTelephonenumber.setText("Telephone Number");

        lblIDnumber.setText("ID Number");

        txtDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDobActionPerformed(evt);
            }
        });
        txtDob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDobKeyPressed(evt);
            }
        });

        lblMobileNumber.setText("mobile Number");

        lblBankAccountNumber.setText("Bank Account number");

        txtSSN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSSNKeyPressed(evt);
            }
        });

        lblDob.setText("DOB");

        lblFaxNumber.setText("Fax Number");

        lblSSN.setText("SSN");

        lblEmail.setText("Email Address");

        lblGeographicData.setText("Geographic Data");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1443816.png"))); // NOI18N
        jLabel3.setText("Photo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIDnumber)
                    .addComponent(lblName)
                    .addComponent(lblGeographicData)
                    .addComponent(lblDob)
                    .addComponent(lblMobileNumber)
                    .addComponent(lblTelephonenumber)
                    .addComponent(lblFaxNumber)
                    .addComponent(lblEmail)
                    .addComponent(lblSSN)
                    .addComponent(lblMedicalRecordNumber)
                    .addComponent(lblHealthPlan)
                    .addComponent(lblBankAccountNumber)
                    .addComponent(lblLicense)
                    .addComponent(lblVehicleNumber)
                    .addComponent(lblLinkedin)
                    .addComponent(lblDeviceIdentifier)
                    .addComponent(lblIP)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBiometric, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBiometric, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(txtIPAddress)
                            .addComponent(txtDevice)
                            .addComponent(txtLinkedin)
                            .addComponent(txtVehicleNumber)
                            .addComponent(txtLicense)
                            .addComponent(txtBank)
                            .addComponent(txtHealthplan)
                            .addComponent(txtMedicalRecord)
                            .addComponent(txtSSN)
                            .addComponent(txtEmail)
                            .addComponent(txtFaxnumber)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtGeographicData, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDob, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMobile, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTelephone, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtIdnumber, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(485, 485, 485))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGeographicData)
                    .addComponent(txtGeographicData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDob)
                    .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMobileNumber)
                    .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelephonenumber)
                    .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFaxNumber)
                    .addComponent(txtFaxnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSN)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicalRecordNumber)
                    .addComponent(txtMedicalRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHealthPlan)
                    .addComponent(txtHealthplan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankAccountNumber)
                    .addComponent(txtBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehicleNumber)
                    .addComponent(txtVehicleNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeviceIdentifier)
                    .addComponent(txtDevice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLinkedin)
                    .addComponent(txtLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIP)
                    .addComponent(txtIPAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBiometric)
                    .addComponent(txtBiometric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 148, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIDnumber))
                .addGap(42, 42, 42))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lblCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(btnSubmit)))
                .addContainerGap(384, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnSubmit)
                .addContainerGap(623, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(!txtName.getText().isEmpty()){
        personaldata.setName(txtName.getText());}
        else{JOptionPane.showMessageDialog(this, "Please enter value");}
        if(!txtGeographicData.getText().isEmpty()){
        personaldata.setGeographicData(txtGeographicData.getText());}
        else{ JOptionPane.showMessageDialog(this, "Please enter value");}
        if(!txtDob.getText().isEmpty()){
        personaldata.setDateOfBirth(txtDob.getText());}
        else{ JOptionPane.showMessageDialog(this, "Please enter value");}
        if(!txtFaxnumber.getText().isEmpty()){
        long fax = Long.parseLong(txtFaxnumber.getText());
        personaldata.setFaxNumber(fax);
        }
        else{
            JOptionPane.showMessageDialog(this, "Please enter value");
        }
        if(!txtEmail.getText().isEmpty()){
        personaldata.setEmailAddress(txtEmail.getText());}
        else{ JOptionPane.showMessageDialog(this, "Please enter value");}
        if(!txtSSN.getText().isEmpty()){
        personaldata.setSsn(txtSSN.getText());}
        else{ JOptionPane.showMessageDialog(this, "Please enter value");} 
        if(!txtMedicalRecord.getText().isEmpty()){
        int medRecord = Integer.parseInt(txtMedicalRecord.getText());
        personaldata.setMedicalRecordNumber((int) medRecord);
        }
        else{ JOptionPane.showMessageDialog(this, "Please enter value");} 
        if(!txtHealthplan.getText().isEmpty()){
        int healthplan = Integer.parseInt(txtHealthplan.getText());
        personaldata.setHealthPlanNumber(healthplan);
        }
        else{ JOptionPane.showMessageDialog(this, "Please enter value");} 
        if(!txtBank.getText().isEmpty()){
        long bank = Long.parseLong(txtBank.getText());
        personaldata.setBankAccountNumber(bank);
        }
        else{ JOptionPane.showMessageDialog(this, "Please enter value");} 
        personaldata.setVehicleIdentifier(txtVehicleNumber.getText());
        if(!txtLicense.getText().isEmpty()){
        long serial = Long.parseLong(txtLicense.getText());
        personaldata.setSerialNumber(serial);
        }
        else{ JOptionPane.showMessageDialog(this, "Please enter value");} 
        personaldata.setLinkedIn(txtLinkedin.getText());
        personaldata.setIpAddress(txtIPAddress.getText());
        personaldata.setBiometricID(txtBiometric.getText());
        personaldata.setIdCode(txtIdnumber.getText());

        JOptionPane.showMessageDialog(this, "Personal data Saved!");

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtDobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDobKeyPressed
       
    }//GEN-LAST:event_txtDobKeyPressed

    private void txtDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDobActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtDobActionPerformed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            txtName.setEditable(true);

        }
        else{
            txtName.setEditable(false);
        }
    }//GEN-LAST:event_txtNameKeyPressed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtIdnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdnumberActionPerformed

    private void txtMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobileActionPerformed

    private void txtFaxnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaxnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxnumberActionPerformed

    private void txtGeographicDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeographicDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeographicDataActionPerformed

    private void txtMobileKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobileKeyPressed
        // TODO add your handling code here:
        String no = txtMobile.getText();
        int lenght = no.length();
        
        char c = evt.getKeyChar();
        if (c>='0' && c<='9'){
            
            if(lenght<10){
                txtMobile.setEditable(true);
            }
            else{
                txtMobile.setEditable(false);
            }
        }else{
            
            if(evt.getExtendedKeyCode()== KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()== KeyEvent.VK_DELETE){
             txtMobile.setEditable(true);   
            }
            else{
                txtMobile.setEditable(false);
            }
        }
        
    }//GEN-LAST:event_txtMobileKeyPressed

    private void txtSSNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSSNKeyPressed
        // TODO add your handling code here:
        String no = txtSSN.getText();
        int lenght = no.length();
        
        char c = evt.getKeyChar();
        if (c>='0' && c<='9'){
            
            if(lenght<9){
                txtSSN.setEditable(true);
            }
            else{
                txtSSN.setEditable(false);
            }
        }else{
            
            if(evt.getExtendedKeyCode()== KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()== KeyEvent.VK_DELETE){
             txtSSN.setEditable(true);   
            }
            else{
                txtSSN.setEditable(false);
            }
        }
        
                             
    }//GEN-LAST:event_txtSSNKeyPressed
private void txtBankKeyPressed(java.awt.event.KeyEvent evt) {                                  
        // TODO add your handling code here:
        String no = txtBank.getText();
        int lenght = no.length();
        
        char c = evt.getKeyChar();
        if (c>='0' && c<='9'){
            
            if(lenght<13){
                txtBank.setEditable(true);
            }
            else{
                txtBank.setEditable(false);
            }
        }else{
            
            if(evt.getExtendedKeyCode()== KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()== KeyEvent.VK_DELETE){
             txtBank.setEditable(true);   
            }
            else{
                txtBank.setEditable(false);
            }
        }
        
                             
    }       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBankAccountNumber;
    private javax.swing.JLabel lblBiometric;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblDeviceIdentifier;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFaxNumber;
    private javax.swing.JLabel lblGeographicData;
    private javax.swing.JLabel lblHealthPlan;
    private javax.swing.JLabel lblIDnumber;
    private javax.swing.JLabel lblIP;
    private javax.swing.JLabel lblLicense;
    private javax.swing.JLabel lblLinkedin;
    private javax.swing.JLabel lblMedicalRecordNumber;
    private javax.swing.JLabel lblMobileNumber;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTelephonenumber;
    private javax.swing.JLabel lblVehicleNumber;
    private javax.swing.JTextField txtBank;
    private javax.swing.JTextField txtBiometric;
    private javax.swing.JTextField txtDevice;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFaxnumber;
    private javax.swing.JTextField txtGeographicData;
    private javax.swing.JTextField txtHealthplan;
    private javax.swing.JTextField txtIPAddress;
    private javax.swing.JTextField txtIdnumber;
    private javax.swing.JTextField txtLicense;
    private javax.swing.JTextField txtLinkedin;
    private javax.swing.JTextField txtMedicalRecord;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtTelephone;
    private javax.swing.JTextField txtVehicleNumber;
    // End of variables declaration//GEN-END:variables
}
