/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.RestaurantAdminRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Restaurant.Restaurant;
import Business.Role.AdminRole;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import static java.time.Clock.system;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rahuludhayakumar
 */

public class AddresJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddresJPanel
     */
    private RestaurantDirectory resDirectory;
    private final JPanel container;
    private final EcoSystem system;
    
    
    
    public AddresJPanel(JPanel container, EcoSystem system, RestaurantDirectory resdirectory) {
        initComponents();
        this.resDirectory = resdirectory;
        this.system = system;
        this.container = container;
        system.setRestaurantDirectory(resdirectory);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddRest = new javax.swing.JLabel();
        pwRestPass = new javax.swing.JPasswordField();
        lblRestAddr = new javax.swing.JLabel();
        txtRestUserName = new javax.swing.JTextField();
        txtRestName = new javax.swing.JTextField();
        txtRestContact = new javax.swing.JTextField();
        lblRestContact = new javax.swing.JLabel();
        btnAddRest = new javax.swing.JButton();
        lblRestPass = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtMgrName = new javax.swing.JTextField();
        lblRestUserName = new javax.swing.JLabel();
        lblMgrName = new javax.swing.JLabel();
        lblRestName = new javax.swing.JLabel();
        txtRestAddr = new javax.swing.JTextField();

        lblAddRest.setBackground(new java.awt.Color(204, 255, 255));
        lblAddRest.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lblAddRest.setForeground(new java.awt.Color(0, 51, 51));
        lblAddRest.setText("Add Restaurant");

        pwRestPass.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        pwRestPass.setForeground(new java.awt.Color(0, 51, 51));
        pwRestPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwRestPassActionPerformed(evt);
            }
        });
        pwRestPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pwRestPassKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwRestPassKeyTyped(evt);
            }
        });

        lblRestAddr.setBackground(new java.awt.Color(204, 255, 255));
        lblRestAddr.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblRestAddr.setForeground(new java.awt.Color(0, 51, 51));
        lblRestAddr.setText("Enter Street Address :");

        txtRestUserName.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtRestUserName.setForeground(new java.awt.Color(0, 51, 51));

        txtRestName.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtRestName.setForeground(new java.awt.Color(0, 51, 51));

        txtRestContact.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtRestContact.setForeground(new java.awt.Color(0, 51, 51));

        lblRestContact.setBackground(new java.awt.Color(204, 255, 255));
        lblRestContact.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblRestContact.setForeground(new java.awt.Color(0, 51, 51));
        lblRestContact.setText("Enter Contact No :");

        btnAddRest.setBackground(new java.awt.Color(204, 255, 255));
        btnAddRest.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnAddRest.setForeground(new java.awt.Color(0, 51, 51));
        btnAddRest.setText("Add");
        btnAddRest.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRestActionPerformed(evt);
            }
        });

        lblRestPass.setBackground(new java.awt.Color(204, 255, 255));
        lblRestPass.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblRestPass.setForeground(new java.awt.Color(0, 51, 51));
        lblRestPass.setText("Set Password :");

        btnBack.setBackground(new java.awt.Color(204, 255, 255));
        btnBack.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 51, 51));
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtMgrName.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtMgrName.setForeground(new java.awt.Color(0, 51, 51));

        lblRestUserName.setBackground(new java.awt.Color(204, 255, 255));
        lblRestUserName.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblRestUserName.setForeground(new java.awt.Color(0, 51, 51));
        lblRestUserName.setText("Set Username :");

        lblMgrName.setBackground(new java.awt.Color(204, 255, 255));
        lblMgrName.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblMgrName.setForeground(new java.awt.Color(0, 51, 51));
        lblMgrName.setText("Manager's Name :");

        lblRestName.setBackground(new java.awt.Color(204, 255, 255));
        lblRestName.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblRestName.setForeground(new java.awt.Color(0, 51, 51));
        lblRestName.setText("Enter Restaurant Name :");

        txtRestAddr.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtRestAddr.setForeground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRestUserName)
                            .addComponent(lblRestName)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRestContact)
                                    .addComponent(lblRestPass)
                                    .addComponent(lblRestAddr)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblMgrName)
                                        .addComponent(btnBack, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtRestAddr)
                                    .addComponent(txtRestUserName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRestName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRestContact, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pwRestPass, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMgrName, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(btnAddRest, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(lblAddRest)))
                .addContainerGap(401, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblAddRest)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRestName)
                    .addComponent(txtRestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRestUserName)
                    .addComponent(txtRestUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRestPass)
                    .addComponent(pwRestPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRestContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRestContact))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRestAddr)
                    .addComponent(txtRestAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMgrName)
                    .addComponent(txtMgrName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddRest)
                    .addComponent(btnBack))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pwRestPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwRestPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwRestPassActionPerformed

    private void pwRestPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwRestPassKeyReleased
        // TODO add your handling code here
    }//GEN-LAST:event_pwRestPassKeyReleased

    private void pwRestPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwRestPassKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_pwRestPassKeyTyped

    private void btnAddRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRestActionPerformed
        // TODO add your handling code here:
        Restaurant object = new Restaurant();
        String customerName = txtRestName.getText();
        String customerContact = txtRestContact.getText();
        String customerAddr = txtRestAddr.getText();
       
        String customerUserName = txtRestUserName.getText();
        String customerPass = String.valueOf(pwRestPass.getPassword());
       
        String mgrName = txtMgrName.getText();

        if( customerName.isEmpty() || customerContact.isEmpty() || customerAddr.isEmpty()  ||
            customerUserName.isEmpty() || customerPass.isEmpty()  || mgrName.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Enter all the required fields!");
        }   else {
            RestaurantDirectory obj1 = new RestaurantDirectory();
            
            object.setResName(customerName);
            object.setResAddress(customerAddr);
            object.setResNo(customerContact);
            object.setResManager(mgrName);
            resDirectory.addRestaurant(object);
            Employee employee = system.getEmployeeDirectory().createEmployee(object.getResNo() );
            system.setRestaurantDirectory(resDirectory);
            UserAccount account = system.getUserAccountDirectory().createUserAccount(customerUserName, customerPass, employee, new AdminRole());
            JOptionPane.showMessageDialog(null, "New Restaurant "+account.getUsername()+" added to the System Successfully!");
           // clearAllFields();
        }
    }//GEN-LAST:event_btnAddRestActionPerformed

     public void clearAllFields() {
        txtRestName.setText("");
        txtRestAddr.setText("");
        txtRestContact.setText("");
        txtRestUserName.setText("");
        pwRestPass.setText("");
        txtMgrName.setText("");
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
       container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        Restaurantdb manageRestJPanel = (Restaurantdb) component;
       // manageRestJPanel.populate();
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRest;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblAddRest;
    private javax.swing.JLabel lblMgrName;
    private javax.swing.JLabel lblRestAddr;
    private javax.swing.JLabel lblRestContact;
    private javax.swing.JLabel lblRestName;
    private javax.swing.JLabel lblRestPass;
    private javax.swing.JLabel lblRestUserName;
    private javax.swing.JPasswordField pwRestPass;
    private javax.swing.JTextField txtMgrName;
    private javax.swing.JTextField txtRestAddr;
    private javax.swing.JTextField txtRestContact;
    private javax.swing.JTextField txtRestName;
    private javax.swing.JTextField txtRestUserName;
    // End of variables declaration//GEN-END:variables
}
