/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.RestaurantAdminRole;

import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rahuludhayakumar
 */
public class Restaurantdb extends javax.swing.JPanel {

    /**
     * Creates new form Restaurantdb
     */
    
       public RestaurantDirectory resDirectory;
    public JPanel container;
    public EcoSystem system;
    public Restaurantdb(JPanel container, EcoSystem system, RestaurantDirectory restaurantDirectory) {
        
        initComponents();
                this.container = container;
        if (system.getRestaurantDirectory() == null) {
            this.resDirectory = new RestaurantDirectory();

        } else {
            this.resDirectory = system.getRestaurantDirectory();
        }
        this.system = system;
        RestaurantDirectory res =system.getRestaurantDirectory();
        populate();
        jPanel1.setVisible(false);
    }
    
       public void populate() {
               DefaultTableModel model = (DefaultTableModel) JTblRestaurants.getModel();
               Object[] row = new Object[7];
        model.setRowCount(0);
//        for (UserAccount userAcc : system.getUserAccountDirectory().getUserAccountList()) {
            for (Restaurant res : resDirectory.getResDirectory()) {
//                if (res.getResNo().equalsIgnoreCase(userAcc.getEmployee().getName())) {
                    
                    row[0] = res.getResNo();
                    row[1] = res.getResName();
                    row[2] = res.getResManager();
                    row[3] = res.getResContact();
                    row[4] = res.getResAddress();
                    row[5] = res.getUname();
                    row[6] = res.getUpass();
                    model.addRow(row);
//                }
//            }
        } //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnAddRest = new javax.swing.JButton();
        btnViewRest = new javax.swing.JButton();
        btnDelRest = new javax.swing.JButton();
        lbl_RestDetails = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTblRestaurants = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtMgrName = new javax.swing.JTextField();
        lblRestAddr = new javax.swing.JLabel();
        lblMgrName = new javax.swing.JLabel();
        txtRestName = new javax.swing.JTextField();
        lblRestName = new javax.swing.JLabel();
        txtRestContact = new javax.swing.JTextField();
        lblRestContact = new javax.swing.JLabel();
        txtRestAddr = new javax.swing.JTextField();
        button1 = new java.awt.Button();

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 51, 51));
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAddRest.setBackground(new java.awt.Color(255, 255, 255));
        btnAddRest.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnAddRest.setForeground(new java.awt.Color(0, 51, 51));
        btnAddRest.setText("Add Restaurant");
        btnAddRest.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRestActionPerformed(evt);
            }
        });

        btnViewRest.setBackground(new java.awt.Color(255, 255, 255));
        btnViewRest.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnViewRest.setForeground(new java.awt.Color(0, 51, 51));
        btnViewRest.setText("View Restaurant");
        btnViewRest.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRestActionPerformed(evt);
            }
        });

        btnDelRest.setBackground(new java.awt.Color(255, 255, 255));
        btnDelRest.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnDelRest.setForeground(new java.awt.Color(0, 51, 51));
        btnDelRest.setText("Delete Restaurant");
        btnDelRest.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelRestActionPerformed(evt);
            }
        });

        lbl_RestDetails.setBackground(new java.awt.Color(204, 255, 255));
        lbl_RestDetails.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lbl_RestDetails.setForeground(new java.awt.Color(0, 51, 51));
        lbl_RestDetails.setText("Restaurants Database");

        JTblRestaurants.setForeground(new java.awt.Color(0, 51, 51));
        JTblRestaurants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Restaurant No", "Name", "Manager", "Contact No", "Address", "Username", "pass"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTblRestaurants);

        txtMgrName.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtMgrName.setForeground(new java.awt.Color(0, 51, 51));

        lblRestAddr.setBackground(new java.awt.Color(204, 255, 255));
        lblRestAddr.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblRestAddr.setForeground(new java.awt.Color(0, 51, 51));
        lblRestAddr.setText("Enter Street Address :");

        lblMgrName.setBackground(new java.awt.Color(204, 255, 255));
        lblMgrName.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblMgrName.setForeground(new java.awt.Color(0, 51, 51));
        lblMgrName.setText("Manager's Name :");

        txtRestName.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtRestName.setForeground(new java.awt.Color(0, 51, 51));

        lblRestName.setBackground(new java.awt.Color(204, 255, 255));
        lblRestName.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblRestName.setForeground(new java.awt.Color(0, 51, 51));
        lblRestName.setText("Enter Restaurant Name :");

        txtRestContact.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtRestContact.setForeground(new java.awt.Color(0, 51, 51));

        lblRestContact.setBackground(new java.awt.Color(204, 255, 255));
        lblRestContact.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        lblRestContact.setForeground(new java.awt.Color(0, 51, 51));
        lblRestContact.setText("Enter Contact No :");

        txtRestAddr.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        txtRestAddr.setForeground(new java.awt.Color(0, 51, 51));

        button1.setLabel("button1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRestName)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblRestAddr)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtRestAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblRestContact)
                                    .addGap(77, 77, 77)
                                    .addComponent(txtRestContact, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(lblMgrName)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtMgrName, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(323, 323, 323)
                    .addComponent(txtRestName, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(114, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMgrName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblRestName)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRestContact)
                            .addComponent(txtRestContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRestAddr)
                            .addComponent(txtRestAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(lblMgrName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(txtRestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(256, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(lbl_RestDetails))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAddRest, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnViewRest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(71, 71, 71)
                                .addComponent(btnDelRest, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(277, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_RestDetails)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnDelRest, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddRest, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnViewRest, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRestActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        AddresJPanel addRestJPanel = new AddresJPanel(container, system, resDirectory);
        container.add(addRestJPanel);
        layout.next(container);
    }//GEN-LAST:event_btnAddRestActionPerformed

    private void btnViewRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRestActionPerformed
        // TODO add your handling code here:
jPanel1.setVisible(true);


    }//GEN-LAST:event_btnViewRestActionPerformed

    private void btnDelRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelRestActionPerformed
                int selectedRow = JTblRestaurants.getSelectedRow();
        int count = JTblRestaurants.getSelectedRowCount();
        if (count == 1) {
            if (selectedRow >= 0) {
                int sb = JOptionPane.YES_NO_OPTION;
                int sr = JOptionPane.showConfirmDialog(null, "Are you sure to delete??", "Warning", sb);
                if (sr == JOptionPane.YES_OPTION) {
                    resDirectory.deleteRestaurant(selectedRow, system);
                    populate();
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Select a Row to continue.");
        }

    }//GEN-LAST:event_btnDelRestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTblRestaurants;
    private javax.swing.JButton btnAddRest;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelRest;
    private javax.swing.JButton btnViewRest;
    private java.awt.Button button1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMgrName;
    private javax.swing.JLabel lblRestAddr;
    private javax.swing.JLabel lblRestContact;
    private javax.swing.JLabel lblRestName;
    private javax.swing.JLabel lbl_RestDetails;
    private javax.swing.JTextField txtMgrName;
    private javax.swing.JTextField txtRestAddr;
    private javax.swing.JTextField txtRestContact;
    private javax.swing.JTextField txtRestName;
    // End of variables declaration//GEN-END:variables


}
