/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.RestaurantAdminRole;

import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rahuludhayakumar
 */
public class Restaurantdb extends javax.swing.JPanel {

    /**
     * Creates new form Restaurantdb
     */
    
       public RestaurantDirectory resDirectory;
    public JPanel container;
    public EcoSystem system;
    public Restaurantdb(JPanel container, EcoSystem system, RestaurantDirectory restaurantDirectory) {
        
        initComponents();
                this.container = container;
        if (system.getRestaurantDirectory() == null) {
            this.resDirectory = new RestaurantDirectory();

        } else {
            this.resDirectory = system.getRestaurantDirectory();
        }
        this.system = system;
        RestaurantDirectory res =system.getRestaurantDirectory();
        populate();
    }
    
       public void populate() {
               DefaultTableModel model = (DefaultTableModel) JTblRestaurants.getModel();
               Object[] row = new Object[7];
        model.setRowCount(0);
//        for (UserAccount userAcc : system.getUserAccountDirectory().getUserAccountList()) {
            for (Restaurant res : resDirectory.getResDirectory()) {
//                if (res.getResNo().equalsIgnoreCase(userAcc.getEmployee().getName())) {
                    
                    row[0] = res.getResNo();
                    row[1] = res.getResName();
                    row[2] = res.getResManager();
                    row[3] = res.getResContact();
                   // row[4] = rest.getRestEmail();
                    row[4] = res.getResAddress();
                   // row[6] = rest.getRestZipCode();
                    model.addRow(row);
//                }
//            }
        } //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnAddRest = new javax.swing.JButton();
        btnViewRest = new javax.swing.JButton();
        btnDelRest = new javax.swing.JButton();
        lbl_RestDetails = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTblRestaurants = new javax.swing.JTable();

        btnBack.setBackground(new java.awt.Color(204, 255, 255));
        btnBack.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 51, 51));
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAddRest.setBackground(new java.awt.Color(204, 255, 255));
        btnAddRest.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnAddRest.setForeground(new java.awt.Color(0, 51, 51));
        btnAddRest.setText("Add Restaurant");
        btnAddRest.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRestActionPerformed(evt);
            }
        });

        btnViewRest.setBackground(new java.awt.Color(204, 255, 255));
        btnViewRest.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnViewRest.setForeground(new java.awt.Color(0, 51, 51));
        btnViewRest.setText("View Restaurant");
        btnViewRest.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRestActionPerformed(evt);
            }
        });

        btnDelRest.setBackground(new java.awt.Color(204, 255, 255));
        btnDelRest.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        btnDelRest.setForeground(new java.awt.Color(0, 51, 51));
        btnDelRest.setText("Delete Restaurant");
        btnDelRest.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelRestActionPerformed(evt);
            }
        });

        lbl_RestDetails.setBackground(new java.awt.Color(204, 255, 255));
        lbl_RestDetails.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lbl_RestDetails.setForeground(new java.awt.Color(0, 51, 51));
        lbl_RestDetails.setText("Restaurants Database");

        JTblRestaurants.setBackground(new java.awt.Color(204, 255, 255));
        JTblRestaurants.setForeground(new java.awt.Color(0, 51, 51));
        JTblRestaurants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Restaurant No", "Name", "Manager", "Contact No", "Email", "Street Address", "Zipcode"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTblRestaurants);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(lbl_RestDetails))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAddRest, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnViewRest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(71, 71, 71)
                                .addComponent(btnDelRest, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_RestDetails)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddRest, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnViewRest, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnDelRest, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(71, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRestActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        AddresJPanel addRestJPanel = new AddresJPanel(container, system, resDirectory);
        container.add(addRestJPanel);
        layout.next(container);
    }//GEN-LAST:event_btnAddRestActionPerformed

    private void btnViewRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRestActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnViewRestActionPerformed

    private void btnDelRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelRestActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnDelRestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTblRestaurants;
    private javax.swing.JButton btnAddRest;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelRest;
    private javax.swing.JButton btnViewRest;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_RestDetails;
    // End of variables declaration//GEN-END:variables


}
